package projectprofile_test

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/vektcore/cortex/internal/infrastructure/projectprofile"
)

// makeTree writes files (and the directories they need) under a temp root. A
// key ending in "/" creates an empty directory, which matters here: most
// decisions in this package hinge on whether a declared path is a directory.
func makeTree(t *testing.T, entries map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for name, content := range entries {
		full := filepath.Join(root, filepath.FromSlash(name))
		if strings.HasSuffix(name, "/") {
			require.NoError(t, os.MkdirAll(full, 0o755))
			continue
		}
		require.NoError(t, os.MkdirAll(filepath.Dir(full), 0o755))
		require.NoError(t, os.WriteFile(full, []byte(content), 0o644))
	}
	return root
}

func load(t *testing.T, root string) projectprofile.Profile {
	t.Helper()
	return projectprofile.Load(context.Background(), root)
}

func patterns(p projectprofile.Profile) []string { return p.ExcludeGlobs() }

func exclusionFor(p projectprofile.Profile, pattern string) (projectprofile.Exclusion, bool) {
	for _, e := range p.Exclusions {
		if e.Pattern == pattern {
			return e, true
		}
	}
	return projectprofile.Exclusion{}, false
}

func notesMentioning(p projectprofile.Profile, substr string) int {
	n := 0
	for _, note := range p.Notes {
		if strings.Contains(note.Reason, substr) {
			n++
		}
	}
	return n
}

// --- tsconfig: the measured case -------------------------------------------

func TestTSConfigExcludeLiteralDirectory(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json":             `{"exclude": ["node_modules", "template"]}`,
		"template/vendor.js":        "var a = 1;",
		"node_modules/dep/index.js": "",
		"src/app.ts":                "",
	})

	p := load(t, root)

	assert.Contains(t, patterns(p), "template/")
	e, ok := exclusionFor(p, "template/")
	require.True(t, ok)
	assert.Equal(t, projectprofile.SourceTSConfig, e.Source)
	assert.Equal(t, "tsconfig.json", e.File)
	assert.Equal(t, "exclude[1]", e.Field)
	assert.Contains(t, e.Reason, "TypeScript")
}

func TestTSConfigAcceptsJSONC(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json": `{
  // generated by tsc --init, see https://example.com/docs
  "compilerOptions": { "strict": true, /* inline */ },
  "exclude": [
    "template", // the vendored kit
  ],
}`,
		"template/x.ts": "",
	})

	p := load(t, root)

	assert.Equal(t, []string{"template/"}, patterns(p))
}

func TestTSConfigCommentMarkerInsideStringIsNotAComment(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json": `{"compilerOptions":{"baseUrl":"https://example.com//x"},"exclude":["template"]}`,
		"template/x.ts": "",
	})

	assert.Equal(t, []string{"template/"}, patterns(load(t, root)))
}

func TestMalformedTSConfigIsANoteNotAFailure(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json": `{"exclude": [`,
		"template/x.ts": "",
	})

	p := load(t, root)

	assert.Empty(t, p.Exclusions, "a file we cannot read is no information, never an exclusion")
	assert.Equal(t, 1, notesMentioning(p, "unreadable"))
}

func TestTSConfigGlobsAreNotTranslated(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json": `{"exclude": ["**/*.spec.ts", "src/**/generated", "template"]}`,
		"template/x.ts": "",
		"src/a.spec.ts": "",
	})

	p := load(t, root)

	assert.Equal(t, []string{"template/"}, patterns(p))
	assert.Equal(t, 2, notesMentioning(p, "globs are not translated"))
}

func TestTSConfigExcludeOutsideRootIsIgnored(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json": `{"exclude": ["../other", "/etc", "."]}`,
	})

	p := load(t, root)

	assert.Empty(t, p.Exclusions)
	assert.Equal(t, 3, notesMentioning(p, "outside the scan root"))
}

func TestTSConfigExcludeOfMissingPathIsNotEmitted(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json": `{"exclude": ["dist"]}`,
	})

	p := load(t, root)

	assert.Empty(t, p.Exclusions)
	assert.Equal(t, 1, notesMentioning(p, "does not exist in the checkout"))
}

func TestTSConfigExtendsLocalBaseIsFollowed(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json":      `{"extends": "./tsconfig.base.json"}`,
		"tsconfig.base.json": `{"exclude": ["template"]}`,
		"template/x.ts":      "",
	})

	p := load(t, root)

	e, ok := exclusionFor(p, "template/")
	require.True(t, ok)
	assert.Equal(t, "tsconfig.base.json", e.File, "credit goes to the file that declared it")
	assert.Contains(t, p.FilesRead, "tsconfig.base.json")
}

func TestTSConfigChildExcludeWinsOverBase(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json": `{"extends": "./base.json", "exclude": ["template"]}`,
		"base.json":     `{"exclude": ["src"]}`,
		"template/x.ts": "",
		"src/a.ts":      "",
	})

	assert.Equal(t, []string{"template/"}, patterns(load(t, root)))
}

func TestTSConfigExtendsPackageIsRecordedNotGuessed(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json": `{"extends": "@tsconfig/next/tsconfig.json"}`,
	})

	p := load(t, root)

	assert.Empty(t, p.Exclusions)
	assert.Equal(t, 1, notesMentioning(p, "extends the package"))
}

func TestTSConfigExtendsCycleTerminates(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json": `{"extends": "./b.json"}`,
		"b.json":        `{"extends": "./tsconfig.json"}`,
	})

	assert.Empty(t, load(t, root).Exclusions)
}

// --- include is informational, never an exclusion ---------------------------

func TestIncludeNarrowsNothingAndExcludesNothing(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json":     `{"include": ["src"]}`,
		"src/a.ts":          "",
		"scripts/deploy.js": "const token = 'x';",
	})

	p := load(t, root)

	assert.Empty(t, p.Exclusions, "scripts/ is not compiled by tsc but it still runs")
	require.Len(t, p.SourceRoots, 1)
	assert.Equal(t, "src", p.SourceRoots[0].Path)
	assert.Equal(t, "include[0]", p.SourceRoots[0].Field)
}

func TestRepositoryWideIncludeIsNoted(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json": `{"include": ["**/*.ts", "**/*.tsx"]}`,
	})

	p := load(t, root)

	assert.Empty(t, p.SourceRoots)
	assert.Equal(t, 2, notesMentioning(p, "repository-wide"))
}

// --- .gitignore -------------------------------------------------------------

func TestGitignoreDirectoryDeclarations(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		".gitignore":            "# deps\n/node_modules\n\n.next/\nout/\nnpm-debug.log*\nlogs\n",
		"node_modules/dep/i.js": "",
		".next/build.js":        "",
		"out/":                  "",
	})

	p := load(t, root)

	assert.ElementsMatch(t, []string{"node_modules/", ".next/", "out/"}, patterns(p))
	e, ok := exclusionFor(p, "node_modules/")
	require.True(t, ok)
	assert.Equal(t, projectprofile.SourceGitignore, e.Source)
	assert.Equal(t, "line 2", e.Field)
}

func TestGitignoreDirectoryThatIsNotInTheCheckoutIsSkipped(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		".gitignore":                  "/out/\nstorybook-static/\n",
		"src/components/out/index.ts": "",
	})

	// A pattern for a path that is not there excludes nothing useful, and
	// "out/" would still hide src/components/out/.
	assert.Empty(t, load(t, root).Exclusions)
}

func TestGitignoreBareNameThatIsNotADirectoryIsSkipped(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		".gitignore": "logs\nsecrets\n",
		"secrets":    "token=1",
	})

	assert.Empty(t, load(t, root).Exclusions, "a bare name may be a file; that is not evidence enough")
}

func TestGitignoreGlobsAreCountedNotTranslated(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		".gitignore": "*.log\n**/public/sw.js\n.yarn/*\n",
	})

	p := load(t, root)

	assert.Empty(t, p.Exclusions)
	assert.Equal(t, 1, notesMentioning(p, "3 glob patterns were not translated"))
}

func TestGitignoreNegationBlocksTheExclusion(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		".gitignore":   "dist/\n!dist/keep.js\n",
		"dist/keep.js": "",
	})

	p := load(t, root)

	assert.Empty(t, p.Exclusions)
	assert.Equal(t, 1, notesMentioning(p, "re-includes part of it"))
}

// --- package.json workspaces ------------------------------------------------

func TestWorkspacesBringTheirOwnTSConfig(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"package.json":               `{"workspaces": ["packages/*"]}`,
		"packages/web/tsconfig.json": `{"exclude": ["template"]}`,
		"packages/web/template/x.ts": "",
		"packages/api/tsconfig.json": `{"exclude": ["legacy"]}`,
		"packages/api/legacy/old.ts": "",
	})

	p := load(t, root)

	assert.ElementsMatch(t, []string{"packages/web/template/", "packages/api/legacy/"}, patterns(p))
	e, ok := exclusionFor(p, "packages/web/template/")
	require.True(t, ok)
	assert.Equal(t, "packages/web/tsconfig.json", e.File)
	assert.Equal(t, []string{"packages/*"}, p.Workspaces)
}

func TestWorkspacesObjectFormIsAccepted(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"package.json":           `{"workspaces": {"packages": ["apps/*"]}}`,
		"apps/web/tsconfig.json": `{"exclude": ["vendored"]}`,
		"apps/web/vendored/a.ts": "",
	})

	assert.Equal(t, []string{"apps/web/vendored/"}, patterns(load(t, root)))
}

func TestPackageFilesIsSeenAndDeliberatelyUnused(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"package.json":  `{"files": ["dist"]}`,
		"scripts/ci.js": "",
	})

	p := load(t, root)

	assert.Empty(t, p.Exclusions)
	assert.Equal(t, 1, notesMentioning(p, "npm publish allowlist"))
}

// --- go.mod -----------------------------------------------------------------

func TestGoModuleIsRecordedAndVendorIsNotExcluded(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"go.mod":                   "module github.com/example/x\n\ngo 1.25\n",
		"vendor/github.com/y/a.go": "package y",
	})

	p := load(t, root)

	assert.Equal(t, "github.com/example/x", p.GoModule)
	assert.Empty(t, p.Exclusions, "vendored Go code is compiled into the binary")
	assert.Equal(t, 1, notesMentioning(p, "compiled into the binary"))
}

// --- composition and reporting ---------------------------------------------

func TestComposeWithKeepsOperatorPatternsFirst(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json": `{"exclude": ["template"]}`,
		"template/x.ts": "",
		".gitignore":    "template/\n",
	})

	p := load(t, root)
	out := p.ComposeWith([]string{"node_modules/", "*.min.js"})

	assert.Equal(t, []string{"node_modules/", "*.min.js", "template/"}, out)
}

func TestComposeWithNeverDropsAnOperatorPattern(t *testing.T) {
	t.Parallel()
	operator := []string{"vendor/", "dist/", "*.min.js"}
	p := load(t, t.TempDir())

	assert.Equal(t, operator, p.ComposeWith(operator))
}

func TestDuplicatePatternKeepsTheStrongerDeclaration(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json": `{"exclude": ["template"]}`,
		"template/x.ts": "",
		".gitignore":    "template/\n",
	})

	p := load(t, root)

	require.Len(t, p.Exclusions, 1)
	assert.Equal(t, projectprofile.SourceTSConfig, p.Exclusions[0].Source)
}

func TestExplainNamesTheAuthorityForEveryExclusion(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json": `{"exclude": ["template"]}`,
		"template/x.ts": "",
	})

	out := load(t, root).Explain()

	assert.Contains(t, out, "exclude template/")
	assert.Contains(t, out, "tsconfig.json exclude[0]")
	assert.Contains(t, out, "read: tsconfig.json")
}

func TestEmptyRepositoryExcludesNothing(t *testing.T) {
	t.Parallel()
	p := load(t, t.TempDir())

	assert.Empty(t, p.Exclusions)
	assert.Empty(t, p.ExcludeGlobs())
	assert.Contains(t, p.Explain(), "declares no manifest")
}

func TestMissingRootIsNotAFailure(t *testing.T) {
	t.Parallel()
	p := load(t, filepath.Join(t.TempDir(), "does-not-exist"))

	assert.Empty(t, p.Exclusions)
}

func TestCancelledContextStopsEarlyWithoutPanicking(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json": `{"exclude": ["template"]}`,
		"template/x.ts": "",
		".gitignore":    "out/\n",
		"out/":          "",
	})

	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	p := projectprofile.Load(ctx, root)

	assert.NotContains(t, p.ExcludeGlobs(), "out/")
}

func TestResultIsDeterministic(t *testing.T) {
	t.Parallel()
	root := makeTree(t, map[string]string{
		"tsconfig.json": `{"exclude": ["template", "legacy"]}`,
		"template/x.ts": "",
		"legacy/y.ts":   "",
	})

	first := load(t, root)
	for range 5 {
		assert.Equal(t, first.ExcludeGlobs(), load(t, root).ExcludeGlobs())
	}
	assert.Equal(t, []string{"legacy/", "template/"}, first.ExcludeGlobs())
}
