#!/usr/bin/env bash
#
# deploy-server.sh — bring up `cortex serve` on a host with Docker.
#
# Run it on the server, as a user in the docker group:
#
#   git clone https://github.com/VektCore/cortex.git && cd cortex
#   ./scripts/deploy-server.sh --domain sast.example.com
#
# Idempotent: run it again to update. It generates the credentials once and
# keeps them in .env, so a second run does not invalidate the API keys clients
# are already using.
#
# What it does NOT do: obtain a TLS certificate or configure your reverse proxy.
# It prints the block you need for Caddy or Nginx, because that part depends on
# what is already listening on port 443.

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 1

COMPOSE_FILE="docs/examples/docker-compose.server.yml"
# Compose resolves relative volume paths against the compose file's directory,
# which would mount the example config instead of the one this script writes.
# --project-directory pins them to the repository root.
COMPOSE=(docker compose -f "docs/examples/docker-compose.server.yml" --project-directory ".")
ENV_FILE=".env"
SERVER_CONFIG="server.yaml"
DOMAIN=""
CLIENT_NAME="cliente"
BUILD_LOCALLY=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --domain)  DOMAIN="$2"; shift 2 ;;
    --client)  CLIENT_NAME="$2"; shift 2 ;;
    --build)   BUILD_LOCALLY=1; shift ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *)         echo "unknown flag: $1" >&2; exit 2 ;;
  esac
done

command -v docker >/dev/null 2>&1 || { echo "docker is not installed" >&2; exit 1; }
docker compose version >/dev/null 2>&1 || {
  echo "the docker compose plugin is not installed" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Credentials — generated once, never regenerated behind your back
# ---------------------------------------------------------------------------

random_secret() { openssl rand -hex 32; }

if [[ ! -f "$ENV_FILE" ]]; then
  echo "generating $ENV_FILE"
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/deploy-server.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Keep this file out of version control and off shared drives.

# API key for the first client. Add more in server.yaml.
CLIENT_ACME_KEY=$(random_secret)

# Shared secret GitHub signs push webhooks with. Paste this into each
# repository's Settings → Webhooks → Secret.
GITHUB_WEBHOOK_SECRET=$(random_secret)

# Token for cloning private repositories, if you scan any. Needs read access
# only. Leave empty for public repositories or if you use an SSH deploy key.
CORTEX_GIT_TOKEN=
EOF
  chmod 600 "$ENV_FILE"
else
  echo "$ENV_FILE already exists — keeping the current credentials"
fi

if [[ ! -f "$SERVER_CONFIG" ]]; then
  echo "copying docs/examples/server.yaml → $SERVER_CONFIG"
  cp docs/examples/server.yaml "$SERVER_CONFIG"
  sed -i.bak "s/- name: acme/- name: $CLIENT_NAME/" "$SERVER_CONFIG" && rm -f "$SERVER_CONFIG.bak"
fi

# ---------------------------------------------------------------------------
# Bring it up
# ---------------------------------------------------------------------------

if [[ $BUILD_LOCALLY -eq 1 ]]; then
  echo "building the image locally (this takes a while: it carries the scanners)"
  "${COMPOSE[@]}" build || exit 1
else
  echo "pulling ghcr.io/vektcore/cortex:latest"
  if ! "${COMPOSE[@]}" pull 2>/dev/null; then
    echo "  pull failed — the image may be private. Either:"
    echo "    - make the package public: GitHub → VektCore → Packages → cortex"
    echo "      → Package settings → Change visibility → Public"
    echo "    - or log in:  echo \$GHCR_TOKEN | docker login ghcr.io -u <user> --password-stdin"
    echo "    - or build it here:  $0 --build"
    exit 1
  fi
fi

"${COMPOSE[@]}" up -d || exit 1

# ---------------------------------------------------------------------------
# Verify
# ---------------------------------------------------------------------------

echo -n "waiting for the server to answer"
for _ in $(seq 30); do
  if curl -fsS http://127.0.0.1:8080/healthz >/dev/null 2>&1; then
    echo " — up"
    break
  fi
  echo -n "."
  sleep 2
done

if ! curl -fsS http://127.0.0.1:8080/healthz >/dev/null 2>&1; then
  echo
  echo "the server did not answer on 127.0.0.1:8080. Logs:"
  "${COMPOSE[@]}" logs --tail=40
  exit 1
fi

# An unauthenticated call must be refused; if it is not, do not put this online.
code=$(curl -s -o /dev/null -w '%{http_code}' -X POST http://127.0.0.1:8080/api/v1/analyses -d '{}')
if [[ "$code" != "401" ]]; then
  echo "REFUSING TO CONTINUE: an unauthenticated request returned $code, not 401."
  echo "Check server.api_keys in $SERVER_CONFIG before exposing this host."
  exit 1
fi
echo "unauthenticated requests are refused (401) — as they should be"

# ---------------------------------------------------------------------------
# What is left for you
# ---------------------------------------------------------------------------

CLIENT_KEY=$(grep '^CLIENT_ACME_KEY=' "$ENV_FILE" | cut -d= -f2)
WEBHOOK_SECRET=$(grep '^GITHUB_WEBHOOK_SECRET=' "$ENV_FILE" | cut -d= -f2)
HOST="${DOMAIN:-your-domain}"

cat <<EOF

───────────────────────────────────────────────────────────────
Cortex is listening on 127.0.0.1:8080. It is NOT exposed yet.

1. Put a TLS-terminating proxy in front. The API keys travel in a header, so
   plain HTTP would hand them to anyone on the path. With Caddy, two lines:

     $HOST {
         reverse_proxy 127.0.0.1:8080
     }

2. Connect a repository — nothing is installed in it. In the repository's
   Settings → Webhooks → Add webhook:

     Payload URL   https://$HOST/api/v1/webhooks/github
     Content type  application/json
     Secret        $WEBHOOK_SECRET
     Events        Just the push event

3. Or ask for an analysis directly:

     curl -X POST https://$HOST/api/v1/analyses \\
       -H "Authorization: Bearer $CLIENT_KEY" \\
       -H 'Content-Type: application/json' \\
       -d '{"repository":"github.com/org/repo","ref":"main"}'

The client key and webhook secret above are in .env. Treat that file as a
credential store: chmod 600, no backups to shared drives.
───────────────────────────────────────────────────────────────
EOF
